#!/bin/bash

# https://owl.cbsi.com/bitbucket/projects/LEADGEN/repos/siege-tools/browse/findJsonDiff

OrigDomain=??
NewDomain=??
Route=$1

curl -s "http://$OrigDomain$Route" > a.json
curl -s "http://$NewDomain$Route" > b.json

echo "Find Diff $Route"
jq -S . a.json > origin_format.json
jq -S . b.json > new_format.json
diff -u origin_format.json new_format.json | colordiff
#diff -u origin_format.json new_format.json | ydiff -s
#git --no-pager diff --no-index origin_format.json new_format.json
#rm -f a.json b.json origin_format.json new_format.json
