#!/usr/bin/env bash

# get "docker service ps" by service_full_name
# Henry Wu 03/2021

verbose="false"

if [[ $# < 1 ]];then
    echo "$0 service_full_name [-v]"
    exit
elif [[ $# > 1 && $2 == '-v' ]]; then
    verbose="true"
fi

svc_name=$1

swarm_manager_name='??'
swarm_manager_ip=$(gcloud compute instances describe $swarm_manager_name --format='get(networkInterfaces[0].networkIP)')

if [[ "$verbose" == "true" ]]; then
    echo -e "swarm_manager: name: $swarm_manager_name; \t ip: $swarm_manager_ip"
fi

docker_svc_id=$(ssh $swarm_manager_ip docker service ls --filter name=$svc_name --format "{{.ID}}")
if [[ "$verbose" == "true" ]]; then
    echo -e "service name: $svc_name; \t id: $docker_svc_id"
fi

ssh $swarm_manager_ip docker service ps $docker_svc_id
